//list of control functions to be included in object class
int object::none(int);
int object::main_stance(int);
int object::main_walk(int);
int object::main_jump(int);
int object::main_duck(int);
int object::main_walkfire(int);
int object::bullet(int);
int object::main_hang(int);
int object::randomdur(int);
int object::main_climb(int);
int object::enemy_pig(int);
int object::enemy_sniper(int);
int object::enemy_boomer(int);
int object::enemy_jet(int);


